In [2]:
# Input / Output
a = input()
print(a)

a


In [3]:
# Mathematical Operator
b = 2 - 2
print(b)

0


In [8]:
# if else
a = 10
if a < 5:
    print("lebih dari 5")
else : 
    print("kurang dari 5")

kurang dari 5


In [ ]:
# Loop
for i in range(5):
    print("test")

test
test
test
test
test


In [9]:
# Function
def printHelloWorld():
    print("Hello World")


printHelloWorld()

Hello World


In [21]:
# Data Structure

## List => Bisa append dan pop
list_1 = [1, "Hello"]
list_1.append(10)
list_1.pop()
list_1

## Tuple => tidak bisa diapa apakan 
tuple_1 = (1,2,3)
tuple_1

## Set => Tidak melihat duplikat 
set_1 = {1,2,3,2,3}
set_1
set_1.remove(2)
set_1

## Dictionary => hubungan antara key dan value
dict_1 = {
   "Name": "Budi",
   "Age": 20,
   "Lulus": False
}

dict_1["Name"]
dict_1["MakananFavorit"] = "Burger"
dict_1


{'Name': 'Budi', 'Age': 20, 'Lulus': False, 'MakananFavorit': 'Burger'}

In [24]:
# Slicing
list = [1,2,3,4,5,6]
#[start:end:step]
print(list[0:6:2])

print(list[::-1])

[1, 3, 5]
[6, 5, 4, 3, 2, 1]


In [25]:
import cv2

In [ ]:
# imread -> membaca image yang mau 
img = cv2.imread("./Session_1/Session_1/photo2.jpg")
# resize -> ngubah ukuran
img = cv2.resize(img, (400, 200))
# cvtColor => ngubah warna
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# imshow -> ngeshow image
cv2.imshow("Kucing", gray)
cv2.waitKey(0)
# imwrite -> buat nulis image
# cv2.imwrite('./Session_1/Session_1/photo2_copy.jpg', img )
cv2.destroyAllWindows()
# ketika dishow butuh satu key untuk direturn, baru nanti dishow 



In [36]:
import numpy as np


In [ ]:
# array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# shape
print(np.shape(a)) # bentuk kolomnya


(2, 3)


In [ ]:
# n-dimension 
print(np.ndim(a))

2


In [ ]:
# zeros
b = np.zeros((3, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [46]:
# ones
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
# empty
d = np.empty((4,3))
print(d)

[[4.67296746e-307 1.69121096e-306 1.20161730e-306]
 [1.42419938e-306 7.56603881e-307 8.45603440e-307]
 [4.45046008e-307 6.23058707e-307 1.11262605e-307]
 [8.62237765e-308 1.20160711e-306 3.75602390e-317]]


In [ ]:
# random
e = np.random.rand(3, 3) * 100
e = np.round(e, 2)
print(e)

[[26.32 27.25 18.29]
 [91.38 61.78 43.06]
 [50.23 57.07 73.94]]


In [ ]:
# vstack & hstack
x = [1, 2, 3]
y = [10, 20, 30]

print(np.vstack((x, y)))
print(np.hstack((x, y)))

[[ 1  2  3]
 [10 20 30]]
[ 1  2  3 10 20 30]
