# Introduction to Python

## input and output

In [ ]:
a = input()

print(a)

dkf


## mathematical operator

In [ ]:
b = 2 + 2

print(b)

4


## conditional statement

In [ ]:
a = 10

if a > 5:
    print('lebih dari 5')
else:
    print('kurang dari 5')

lebih dari 5


## looping

In [ ]:
for i in range(5):
    print('tes')

tes
tes
tes
tes
tes


## definition/function

In [9]:
def printHelloWorld():
    print('Hello World!')

printHelloWorld()

Hello World!


## list

In [10]:
list_1 = [1, 'halo']
list_1.append(10)
list_1.pop()
list_1.pop()
list_1

[1]

## tuple

In [12]:
tuple_1 = (1, 2, 3)
tuple_1

(1, 2, 3)

## set

In [14]:
set_1 = {1, 2, 2, 3, 3}
set_1

{1, 2, 3}

## dictionary

In [19]:
dict_1 = {
    'Name': 'Budi',
    'Age': 20,
    'Lulus': False
}

print(dict_1)

dict_1['Makanan Favorit'] = 'Burger'

print(dict_1)

{'Name': 'Budi', 'Age': 20, 'Lulus': False}
{'Name': 'Budi', 'Age': 20, 'Lulus': False, 'Makanan Favorit': 'Burger'}


## slicing

In [24]:
list = [1, 2, 3, 4, 5, 6]

# list[start:end:step]
print(list[:2])

print(list[::2])

print(list[::-1])

[1, 2]
[1, 3, 5]
[6, 5, 4, 3, 2, 1]


# Actual Material (cv2 / image processing)

In [26]:
import cv2

cv2 functions breakdown
- imread -> read image
- imshow -> show image
- imwrite -> writting image
- cvtColor -> change color
- resize -> change size

In [39]:
img = cv2.imread('./Session_1/Session_1/photo2.jpg')
img = cv2.resize(img, (400, 200))

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow('Cat', gray)
cv2.waitKey(0)
# cv2.imwrite('photo2_copy.jpg', img)
cv2.destroyAllWindows()

# Numpy

In [40]:
import numpy as np

## array

### 2d array

In [41]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


### 3d array

In [48]:
b = np.array([
    (1, 2, 3),
    (4, 5, 6)
])

print(b)
print(np.shape(b))
print(np.ndim(b))

[[1 2 3]
 [4 5 6]]
(2, 3)
2


### zeros

In [50]:
zeroes = np.zeros((3, 3))

print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### ones

In [51]:
c = np.ones((3, 3))

print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### empty

In [53]:
d = np.empty((4, 3))

print(d)

[[1.01855798e-312 1.12465777e-312 1.01855798e-312]
 [9.54898106e-313 1.20953760e-312 1.03977794e-312]
 [1.23075756e-312 1.08221785e-312 1.08221785e-312]
 [9.76118064e-313 1.18831764e-312 1.90979621e-312]]


### random

In [56]:
e = np.random.rand(3, 3) * 100

print(e)

[[13.30059358 10.98232426 89.79565245]
 [16.750964   30.94319995 59.70247783]
 [70.21838573 67.47278725 21.97673339]]


### vstack -> vertical stacking

In [58]:
x = [1, 2, 3]
y = [10, 20, 30]

print(np.vstack((x, y)))

[[ 1  2  3]
 [10 20 30]]


### hstack -> horizontal stacking

In [59]:
x = [1, 2, 3]
y = [10, 20, 30]

print(np.hstack((x, y)))

[ 1  2  3 10 20 30]
